apiVersion : apps/v1
kind: Deployment
metadata:
  name: helloworldjayr 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldjayr


      template:
    metadata:
      labels:
        version: 1.0.0
        api: private
        app: helloworldjayr
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name:  helloworldjayr
          image: ovcoderegistry.azurecr.io/helloworldjayr:1.0.0
          resources:
          ports:
          - containerPort: 3000
          #envFrom:
          #- secretRef:
          #    name: gemcircle-accountquerysvc


          #iask ni diri
      imagePullSecrets:
        - name: container-registry
