apiVersion: v1
kind: Service
metadata:
    name: helloworldjayr
spec:
    type: ClusterIP
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: helloworldjayr
    
    
    
    #type: LoadBalancer
    #ports:
    #- port: 3000 
    #selector:
    #    app: helloworldjayr